# Numpy

In [1]:
import numpy as np

In [3]:
np.array

<function numpy.array>

In [4]:
np.array(object,dtype=None, copy=True, order=None, subok=False,ndmin=0)

array(<class 'object'>, dtype=object)

The above constructor takes the following parameters:
               * Object-----> Any object exposing the array interface method returns an array, or any nested sequence.
               
               * dtype -----> Desired data type of array, optinal
               * copy-------> Optional. By default(true), the object is copied.
               * order------> C(row major) or F (column major) or A(any) default.
              * subok------> By default, returned array forced to be a base class array. If ture, sub classes passed though.
               * ndmin------> Specifies minimum dimensions of resultant array.

In [5]:
import numpy as np

a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
# more than one dimenson
import numpy as np

a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [8]:
a = np.array([[[1,2],[3,4],[5,6]]])
print(a)

[[[1 2]
  [3 4]
  [5 6]]]


In [11]:
# Minimum dimensions
import numpy as np

a= np.array([1,2,3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [13]:
# dtype parameter

import numpy as np

a= np.array([1,2,3], dtype=complex)

print(a)

'''The ndarray object consists of contigious one-dimension segment of computer memory, combined with an indeding scheme that maps each items to a location in the memory block. The memory blcok holds the elements in a a row-major order or a column-major order(FORTRAN or MatLab style)'''

[1.+0.j 2.+0.j 3.+0.j]


'The ndarray object consists of contigious one-dimension segment of computer memory, combined with an indeding scheme that maps each items to a location in the memory block. The memory blcok holds the elements in a a row-major order or a column-major order(FORTRAN or MatLab style)'

# Numpy Data types

          *Data_Types-----------> Description
          
          * bool_---------------> Boolean(True or False) Stroed as byte.
          * int_----------------> Default integer type(same as C long; normally either int64 or int32)
          * intc----------------> Identical to C int(normally int32 or int64)
          * intp----------------> Integer used for indexing (same as C size_t; normally either int32 or int64)
          * int8----------------> Byte(-128 to 127)
          * int32---------------> Integer(-32768 to 32767)
          * int64---------------> Integer (-9223372036854775808  to 9223372036854775807)
          * uint8---------------> Unsigned intger(0 to 255)
          * uint16--------------> Unsigend integer(0 to 65535)
          * uint32--------------> Unsigend integer(0 to 4294967295)
          * uint64--------------> Unsigned integer(0 to 18446744073709551615)
          * float_--------------> Shorthand for float64
          * float16-------------> Half precision float: sign bit, 5 bit exponent, 10 bits mantissa
          * float32-------------> Single precision float: sign bit, 8 bits exponent, 23 bits mantissa.
          * float64-------------> Double precison float; sign bit, 11 bits exponent, 52 bits mantissa.
          * complex_------------> Shorthand for complex128
          * complex64-----------> Complex number, represented by two 32-bit floats(real and imaginary components)
          * complex128----------> Complex number, represented by two 64-bit floats(real and imaginary components)

In [17]:
# using array-scalar type

import numpy as np

dt=np.dtype(np.int32)
print(dt)

int32


In [18]:
# int8,int16,int32, int64 can be replaced by equivalent string'i1','i2','i4','i8'
dt=np.dtype('i4')
dt

dtype('int32')

In [19]:
dt=np.dtype('>i4')
dt

dtype('>i4')

In [23]:
# First create structured data type

import numpy as np

dt= np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [30]:
# now apply it to ndarray object

import numpy as np

dt=np.dtype([('age',np.int8)])
a= np.array([(10,),(20,),(30)], dtype=dt)
print(a)

[(10,) (20,) (30,)]


In [31]:
# file name can be used to access content of age column

import numpy as np
dt= np.dtype([('age', np.int8)])
a = np.array([(10,),(20,),(30)], dtype=dt)
print(a['age'])

[10 20 30]


In [32]:
import numpy as np

student=np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [35]:
import numpy as np

student=np.dtype([('name','S20'),('age','i1'),('marks','f4')])
a=np.array([('Ayush',21,50),('Kartik',18,70)],dtype=student)
print(a)

[(b'Ayush', 21, 50.) (b'Kartik', 18, 70.)]


Each build-in data type has a character code that uniquely identifies it.

    * 'b': boolean
    * 'i': (signed) integer
    * 'u': unsigned integer
    * 'f': floating-point
    * 'c': complex-floating point
    * 'm': timedelta
    * 'M': datetime
    * 'O': (python) Objects
    * 'S','a': (byte-) string
    * 'U': Unicode
    * 'V': raw data(void)


In [40]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [41]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [6]:
import numpy as np

a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print(a.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [43]:
print(a.shape)

(1, 3, 3)


In [5]:
# NumPy also provides a reshape function to resize an array.

import numpy as np

a = np.array([[1,2,3],[4,5,6]])

b= a.reshape(3,2)
print(b)
print(b.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [4]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

b= a.reshape(2,3)
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [2]:
# an array of evenly spaced numbers

import numpy as np

a =  np.arange(24)
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
# this is one dimentional array

import numpy as np

a = np.arange(24)
print(a.ndim)


# now reshape it

b = a.reshape(2,4,3)
print(b)
print(b.ndim)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [19]:
# dtype of array is int8 (1 byte)

import numpy as np

x = np. array([1,2,3,4,5], dtype=np.int8)

print(x.itemsize)

1


In [20]:
# dtype of array is int8 (1 byte)

import numpy as np

x = np. array([1,2,3,4,5], dtype=np.int16)

print(x.itemsize)

2


In [21]:
# dtype of array is int8 (1 byte)

import numpy as np

x = np. array([1,2,3,4,5], dtype=np.int32)

print(x.itemsize)

4


In [22]:
# dtype of array is int8 (1 byte)

import numpy as np

x = np. array([1,2,3,4,5], dtype=np.int64)

print(x.itemsize)

8


In [26]:
# dtype of array is float32 (4 byte)

import numpy as np

x = np. array([1,2,3,4,5], dtype=np.float32)

print(x.itemsize)

4


# numpy.flags

The ndarray object has the following attributes. Its current value are returned by this  functions

        * C_CONTIGUOUS(C):----------> The data is in a single, C-style contiguous segment.
        * F_CONTIGUOUS(F):----------> The data is in a single, Fortran-style contiguous segment.
        * OWNDATA(O):---------------> The array owns the memory it uses or borrows it from another objects.
        * WRITEABLE (W):------------> The data area can be written to. Setting this to False locks the data, making it read only.
        * ALIGNED(A):---------------> The data and all elements are aligned appropriately for the hardware.
        * UPDATEIFCOPY(U):----------> This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array.

In [27]:
import numpy as np

x = np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



# numpy. empty

A new ndarray object can be constructed by any of the following array creation routines or using a low-level ndarray constructor.

* It creates unintialized array of specified shape and dtype. It uses the following constructor:

 The constructor takes the following parameters.

    * Shape ------------> Shape of an empty array in int or tuple of int.
    * Dtype-------------> Desired output data type. Optional
    * Order-------------> 'c' for C-style row-major array. 'F' for FORTRAN style column-major array.

In [33]:
import numpy as np
x = np.empty([3,2], dtype=int)
print(x)

# The element in an array show random values as they are initialized.

[[1 2]
 [3 4]
 [5 6]]


In [34]:
# array of five zeros. Default dtype is float.

import numpy as np

x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [43]:
import numpy as np

x = np.zeros((5), dtype=np.int8)
print(x)

[0 0 0 0 0]


In [38]:
# Custom type

import numpy as np

x = np.zeros((2,2), dtype=[('x','i4'),('y','i4')])
print(x)
print(x.ndim)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
2


# numpy.ones

Return a new array of specified size and type, filled with ones.

The constructor takes the following parameter

    * Shape ---------------> Shape of an empty array in int or tuple of int.
    * Dtype ---------------> Desired output data type. Optional.
    * Order ---------------> 'C' for C-style row-major array, 'F' for FORTRAN Style column-major array

In [48]:
# Array of five ones. Default dtype is float.


import numpy as np
x = np. ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [49]:
# Array of five ones. Default dtype is float.


import numpy as np
x = np. ones((5), dtype=int)
print(x)

[1 1 1 1 1]


In [51]:
import numpy as np

x= np. ones([2,2], dtype=int)
print(x)

[[1 1]
 [1 1]]


# numpy. asarray

This function is similar to numpy.array except for the fact that it has fewer parameters. This
routine is useful for converting Python Sequence into ndarray.

* The Constructor takes the following parameters.

           * a ----------> Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists.
           * dtype ------> By default, the data type of input data is applied to the resultant ndarray.
           * order-------> C(row major) or F(colum major), C is default.

In [53]:
# convert list to ndarray.

import numpy as np

x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [56]:
# dtype is set
import numpy as np

x = [1,2,3]
a = np.asarray(x, dtype=float)
print(a)

[1. 2. 3.]


In [57]:
# ndarray from tuple

import numpy as np

x= (1,2,3)

a= np.asarray(x)
print(a)

[1 2 3]


In [62]:
# ndarray form list of tuples.

import numpy as np

x=[(1,2,3),(4,5)]
a = np.array(x)
print(a)

[(1, 2, 3) (4, 5)]


C:\Users\ROUSHA~1\AppData\Local\Temp/ipykernel_17764/1517367955.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array(x)


# numpy. frombuffer

This function interprets a buffer as one-dimensional array. Any object that exposes the buffer interface is used as parameter to return an ndarray.

The constructor takes the following parameters.

        * buffer-------------> Any object that exposes buffer interface
        
        * dtype--------------> Data type of returned ndarray. Defaults to float.
        
        * count--------------> The number of items to read, default-1 means all data.
        
        * offset-------------> The starting position to read from. Default is 0

In [74]:
import numpy as np

s = b'Hello World'

a = np.frombuffer(s, dtype='S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']
