# Numpy

In [1]:
import numpy as np

In [3]:
np.array

<function numpy.array>

In [4]:
np.array(object,dtype=None, copy=True, order=None, subok=False,ndmin=0)

array(<class 'object'>, dtype=object)

The above constructor takes the following parameters:
               * Object-----> Any object exposing the array interface method returns an array, or any nested sequence.
               
               * dtype -----> Desired data type of array, optinal
               * copy-------> Optional. By default(true), the object is copied.
               * order------> C(row major) or F (column major) or A(any) default.
              * subok------> By default, returned array forced to be a base class array. If ture, sub classes passed though.
               * ndmin------> Specifies minimum dimensions of resultant array.

In [5]:
import numpy as np

a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
# more than one dimenson
import numpy as np

a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [8]:
a = np.array([[[1,2],[3,4],[5,6]]])
print(a)

[[[1 2]
  [3 4]
  [5 6]]]


In [11]:
# Minimum dimensions
import numpy as np

a= np.array([1,2,3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [13]:
# dtype parameter

import numpy as np

a= np.array([1,2,3], dtype=complex)

print(a)

'''The ndarray object consists of contigious one-dimension segment of computer memory, combined with an indeding scheme that maps each items to a location in the memory block. The memory blcok holds the elements in a a row-major order or a column-major order(FORTRAN or MatLab style)'''

[1.+0.j 2.+0.j 3.+0.j]


'The ndarray object consists of contigious one-dimension segment of computer memory, combined with an indeding scheme that maps each items to a location in the memory block. The memory blcok holds the elements in a a row-major order or a column-major order(FORTRAN or MatLab style)'

# Numpy Data types

          *Data_Types-----------> Description
          
          * bool_---------------> Boolean(True or False) Stroed as byte.
          * int_----------------> Default integer type(same as C long; normally either int64 or int32)
          * intc----------------> Identical to C int(normally int32 or int64)
          * intp----------------> Integer used for indexing (same as C size_t; normally either int32 or int64)
          * int8----------------> Byte(-128 to 127)
          * int32---------------> Integer(-32768 to 32767)
          * int64---------------> Integer (-9223372036854775808  to 9223372036854775807)
          * uint8---------------> Unsigned intger(0 to 255)
          * uint16--------------> Unsigend integer(0 to 65535)
          * uint32--------------> Unsigend integer(0 to 4294967295)
          * uint64--------------> Unsigned integer(0 to 18446744073709551615)
          * float_--------------> Shorthand for float64
          * float16-------------> Half precision float: sign bit, 5 bit exponent, 10 bits mantissa
          * float32-------------> Single precision float: sign bit, 8 bits exponent, 23 bits mantissa.
          * float64-------------> Double precison float; sign bit, 11 bits exponent, 52 bits mantissa.
          * complex_------------> Shorthand for complex128
          * complex64-----------> Complex number, represented by two 32-bit floats(real and imaginary components)
          * complex128----------> Complex number, represented by two 64-bit floats(real and imaginary components)

In [17]:
# using array-scalar type

import numpy as np

dt=np.dtype(np.int32)
print(dt)

int32


In [18]:
# int8,int16,int32, int64 can be replaced by equivalent string'i1','i2','i4','i8'
dt=np.dtype('i4')
dt

dtype('int32')

In [19]:
dt=np.dtype('>i4')
dt

dtype('>i4')

In [23]:
# First create structured data type

import numpy as np

dt= np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [30]:
# now apply it to ndarray object

import numpy as np

dt=np.dtype([('age',np.int8)])
a= np.array([(10,),(20,),(30)], dtype=dt)
print(a)

[(10,) (20,) (30,)]


In [31]:
# file name can be used to access content of age column

import numpy as np
dt= np.dtype([('age', np.int8)])
a = np.array([(10,),(20,),(30)], dtype=dt)
print(a['age'])

[10 20 30]


In [32]:
import numpy as np

student=np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [35]:
import numpy as np

student=np.dtype([('name','S20'),('age','i1'),('marks','f4')])
a=np.array([('Ayush',21,50),('Kartik',18,70)],dtype=student)
print(a)

[(b'Ayush', 21, 50.) (b'Kartik', 18, 70.)]


Each build-in data type has a character code that uniquely identifies it.

    * 'b': boolean
    * 'i': (signed) integer
    * 'u': unsigned integer
    * 'f': floating-point
    * 'c': complex-floating point
    * 'm': timedelta
    * 'M': datetime
    * 'O': (python) Objects
    * 'S','a': (byte-) string
    * 'U': Unicode
    * 'V': raw data(void)


In [40]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [41]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [42]:
import numpy as np

a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [43]:
print(a.shape)

(1, 3, 3)


In [47]:
# NumPy also provides a reshape function to resize an array.

import numpy as np

a = np.array([[1,2,3],[4,5,6]])

b= a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]
